services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning

  writedb:
    image: clue/json-server
    ports:
      - 4000:80
    volumes:
      - "json-server/readdb.json:/data/db.json"

  readdb:
    image: clue/json-server
    ports:
      - 3000:80
    volumes:
      - "json-server/writedb.json:/data/db.json"